bailly_weird = {
    "μηνύω": "<i>υ touj. long au fut. et à l’ao. au prés. et à l’impf. ; long chez les Att., commun chez les Épq. et Pind. dev. une voy. brève</i>",
    "διαφύω": "ῠ, <i>mais v. ci-dessous</i>",
    "φλεγμαίνω": "<i>Le second ε dans ἐφλέγμαινεν bref,</i> AR. <i>Vesp. 277</i>",
    "γερμανία": "μᾱ, <i>mais v. ci-dessous</i>",
    "ὑλακόεις": "ῡ <i>à l’arsis,</i> ᾰ",
    "ἁγής": "ᾰ <i>par exc</i>.",
    "ἀράομαι": "ᾱρ HOM. ; ᾰρ ATT. ; ρᾱ <i>fut. et ao</i>.",
    "μύωψ": "ῡ <i>v. ci-dessous</i>",
    "ἀνοδύρομαι": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ἀνιμάω": "ῐ ; <i>ao. et pf</i>. ῑ",
    "συναμύνω": "ᾰῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "καταράομαι": "ᾰρ, <i>épq</i>. ᾱρ",
    "πολυανακτίδης": "ᾰνῐ, <i>gén</i>. ᾱο",
    "ἰταλία": "⏑⏑⏑‒, <i>dans les vers dactyliques</i> ‒⏑⏑‒",
    "ἁλινήκτειρα": "ᾰῑ <i>p</i>. ᾰῐ",
    "σικελίδης": "σῑ <i>par nécess. prosod</i>.",
    "ὑσγινόεις": "ῑ, <i>p. exc</i>. ῐ",
    "ἀμυκοφόνος": "ᾰῡ <i>par nécessité prosod. p</i>. ῠ",
    "ἄεσα": "ᾰε <i>mais</i> ᾱε <i>à l’arsis</i>",
    "ἀποδίομαι": "ᾱ <i>à l’arsis</i>",
    "χαλκεών": "εω <i>monosyll</i>.",
    "μικρός": "ῑ, <i>postér</i>. ῐ",
    "συγκρίνω": "ῑ <i>prés.,</i> ῐ <i>fut</i>.",
    "πατρῷος": "ω <i>bref</i>",
    "δάφνις": "ᾱ, <i>mais v. ci-dessous</i>",
    "ὁμοίϊος": "ϊ <i>bref, mais long dev. une finale longue,</i> IL. <i>9, 440 ; 13, 356, 635</i>",
    "νισυρῖτις": "ῑῡῑῐδ ; <i>p. except</i>. ῐῠ",
    "ἀρά": "ᾰρ, <i>épq. à l’arsis</i> ᾱρ",
    "πληθύς": "ῡ <i>nom. et acc. sg. ;</i> ῠ <i>aux autres cas</i>",
    "πανάπαλος": "πᾱν <i>par nécess. prosod. au commenc. du vers,</i> ᾰᾰ",
    "ὅτι": "ῐ, <i>v. ci-dessous</i>",
    "κυανόπεπλος": "ῡ <i>irrég. ;</i> ᾰ",
    "βραδύνω": "ᾰ, ῡ <i>excepté fut. et pl.q.pf</i>.",
    "ἀρτύνω": "ῡ, <i>excepté au fut</i>.",
    "ὀφιόνεος": "<i>irrég</i>. ῑ",
    "συναρτύνω": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ἀναπτύω": "ῡ <i>par nécessité prosod</i>.",
    "κωκύω": "<i>pour la quantité v. ci-dessous</i>",
    "τορύνω": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ὑπερθύω": "θῡ, <i>par licence</i> θῠ",
    "βιθυνηΐς": "ῐῠ <i>par licence p</i>. ῑῡ",
    "ἀπολοφύρομαι": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ἀφίημι": "<i>Dans Hom. et les Épq. d’ord</i>. ῐ <i>prés.,</i> ῑ <i>temps à augment ; dans les Att. touj</i>. ῑ",
    "κυδαθηναιεύς": "ῡ, <i>mais v. ci-dessous</i>",
    "ὀρχηστύς": "ῡ <i>nom. et acc</i>.",
    "συμπαρακατακλίνω": "ῑ <i>prés.,</i> ῐ <i>fut</i>.",
    "συγκλίνω": "ῑ <i>prés.,</i> ῐ <i>fut</i>.",
    "κλυτόνοος": "ῡ <i>par exc. à l’arsis</i>",
    "πωλιανός": "ᾰ <i>par nécessité prosodique</i>",
    "καταμύω": "ῡ <i>prés. et impf.,</i> ῠ <i>fut. et ao</i>.",
    "νηδύς": "ῠ <i>dans les formes trisyll. ;</i> ῡ <i>dans les formes dissyll. excepté</i> EUR. <i>Cycl. 570 ; Andr. 356 ;</i> CALL. <i>Dian. 160</i>",
    "τριτάλας": "ῐ, <i>masc</i>. ᾰᾱ, <i>neutre</i> ᾰᾰ",
    "μυδαλέος": "ῠᾰ, <i>irrég. dans les vers daclyliques</i> ῡᾰ",
    "δάμαρ": "δᾰ, <i>nomin</i>. ᾰρ",
    "ἀχλύς": "ᾱ ; ῡ <i>nom. et acc., mais v. ci-dessous ;</i> ῠ <i>gén. et dat</i>.",
    "τραχύνω": "ᾱῡ, <i>au fut. act</i>. ῠ",
    "κυανόπεζα": "ῡ <i>irrég. ;</i> ᾰ",
    "πλημμυρίς": "ῡ, <i>mais v. ci-dessous</i>",
    "τάλας": "<i>nom. masc</i>. ᾰᾱ ; <i>fém</i>. ᾰᾰ ; <i>neutre</i> ᾰᾰ ; <i>voc. masc</i>. ᾰᾰ, <i>gén. masc</i>. ᾰᾰ",
    "σφοδρύνω": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "κάσπιος": "ῐ, <i>mais</i> ῑ <i>devant les syllabes longues</i>",
    "τανύω": "ᾰ, ῠ <i>aux prés., fut. et ao. act</i>.",
    "ἁλίβαπτος": "ᾰ, ῑ <i>pour</i> ῐ <i>à l’arsis</i>",
    "ῥυθμός": "ῡ, <i>att</i>. ῠ",
    "ἅπας": "ᾰπᾱς, <i>neutre</i> ᾰπᾱν, <i>mais</i> ᾰπᾰν, HOM. <i>v. ci-dessous</i>",
    "συμφύρω": "φῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "πλανόδιος": "ᾱν <i>par nécessité métr. p</i>. ᾰν",
    "ἀνηπύω": "ῠ, A. RH. <i>4, 1197 ;</i> ῡ, MOSCH. <i>2, 98</i>",
    "βέβρυξ": "υ, <i>v. ci-dessous</i>",
    "βραχύνω": "ᾰ ; ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "θεά": "θεά <i>monosyll. par syniz. dans</i> πότνια θεά, OD. <i>5, 215 ; 13, 391 ; 20, 61 ;</i> EUR. <i>Andr. 978</i>",
    "διόγονος": "ῑ <i>par exc</i>.",
    "συναπευθύνω": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "γερμανικός": "ᾱ, <i>mais v. ci-dessous</i>",
    "λολλιανός": "ᾰ <i>par nécessité prosod</i>.",
    "συνεχής": "ῠ, <i>épq</i>. ῡ <i>à l’arsis</i>",
    "ἀποφθίνω": "<i>v. la quantité ci-dessous</i>",
    "γέφυρα": "ῡ, <i>mais v. ci-dessous</i>",
    "μηνίω": "ῑ <i>devant</i> σ ; ι <i>devant une voy. long à l’arsis, bref à la thésis</i>",
    "πόστουμος": "ου <i>bref</i>",
    "μύω": "ῡ <i>v. ci-dessous</i>",
    "δακρύω": "αῡ <i>à tous les temps ; mais v. fin</i>",
    "ὑδογενής": "ῠ, <i>par nécess. pros</i>. ῡ",
    "ὑποδεξίη": "ῐ, <i>p. exc</i>. ῑ",
    "λοξόβαμος": "ᾰ <i>par nécess. métr. p</i>. ᾱ",
    "ῥύομαι": "υ <i>prés. et impf. ;</i> ῡ <i>f. et ao</i>. ATT.",
    "τοιοῦτος": "<i>La 1<sup>re</sup> syll. de</i> τοιοῦτος <i>chez les poètes att. plus souv. brève que longue,</i> ESCHL. <i>Suppl. 181 ;</i> SOPH. <i>O.R. 674, O.C. 642, etc. ; chez Hom. longue, chez Pindare longue une fois,</i> PD. <i>P. 8, 78</i>",
    "ἰαίνω": "ῐ <i>au prés.,</i> ῑ <i>aux temps second. à cause de l’augment, et au sbj. ao</i>. OD. <i>22, 59</i>",
    "ἀπείρατος¹": "ρᾰ <i>p. licence poét. p</i>. ρᾱ",
    "σκαλαθύρω": "ᾰᾰ, ῡ <i>prés</i>. ῠ <i>fut</i>.",
    "πάτρα": "ᾱ <i>fin</i>.",
    "μονόλυκος": "νο̄, <i>à cause de la forme primit. de</i> λύκος = *ϝλύκος <i>cf. sscr</i>. vrkas",
    "ἰοειδής¹": "ῐ, <i>par licence p</i>. ῑ",
    "παράλιος": "πᾰᾰλ, <i>mais v. ci-dessous</i>",
    "ταχύνω": "ᾰῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ἰασώ": "ῑᾱ, <i>mais v. ci-dessous</i>",
    "συμπληθύνω": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "νέκυς": "ῠ <i>à tous les cas ; chez Hom. ῡ au nom. et à l’acc. sg</i>.",
    "στάχυς": "ᾰ, ῡ <i>aux cas dissyll. chez les Att.,</i> ῠ <i>chez les poètes postér. v. ci-dessous ;</i> ῠ <i>aux cas trisyll</i>.",
    "αἰσχύνω": "ῡ, <i>fut</i>. ῠ",
    "ἀδορύληπτος": "ῠ <i>ou</i> ῐ",
    "συβόσιον": "ῑ IL. <i>11, 679 ;</i> OD. <i>14, 101</i>",
    "συμπαχύνω": "ᾰ ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "νάω": "<i>avec</i> ᾱ",
    "φρέαρ": "ᾱρ, ᾱτ <i>att.,</i> ᾰτ <i>épq. et qqf. com</i>.",
    "λυσιπαίγμων": "ῠ <i>par nécess. prosod</i>.",
    "τίνω": "<i>au prés</i>. ῑ <i>épq.,</i> ῐ <i>att. ; aux autres temps</i> ῐ",
    "ἵημι": "l’ι <i>initial est bref en gén. à l’act. dans HOM. et les épiques, long (excepté dans</i> ESCHL. <i>Sept. 310, 493 et dans</i> EUR. <i>I.A. 298) chez les Att</i>.",
    "φάος": "ᾰ, <i>mais v. ci-dessous</i>",
    "κωλύω": "ῠ <i>prés. et impf. ;</i> ῡ <i>aux autres temps</i>",
    "ἡρωϊκός": "ω <i>bref</i>",
    "συμμαρτύρομαι": "τῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "συναναφύρω": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ἀπείρατος": "ρᾰ <i>p. licence poét. p</i>. ρᾱ",
    "φθίω": "ῑ <i>dans</i> φθίω, OD. <i>2, 368 ;</i> ῐ <i>dans</i> ἔφθιεν, IL. <i>18, 446 ; aux autres temps ῑ épq., ῐ att. ; v. le moy</i>.",
    "ὑγρύνω": "ῡν <i>prés.,</i> ῠν <i>fut</i>.",
    "περικλάω": "ᾰ <i>à tous les temps</i>",
    "πεδίον": "ᾱ <i>à l’arsis</i>",
    "λυσιπήμων": "ῠ <i>par nécess. prosod</i>.",
    "φίλος": "ῐ, <i>v. fin</i>",
    "μαρκιάνη": "ᾰν <i>par nécessité prosod. p</i>. ᾱν",
    "συναλγύνω": "γῠ <i>prés.,</i> ῠ <i>fut</i>.",
    "κῆρυξ": "<i>nom. et voc</i>. ῠ, <i>cas obl</i>. ῡ",
    "ὀφρύς": "ῡ <i>au nom. et à l’acc. sg. ; dans les composés</i> ῠ, <i>v</i>. εὔοφρυς, λεύκοφρυς, <i>etc</i>.",
    "συνανακλίνω": "ῑ <i>prés.,</i> ῐ <i>fut</i>.",
    "χηραμοδύτης": "ᾰ, ῠ, <i>mais ῡ à l’arsis</i>",
    "ἀναβολίη": "<i>réf. non retrouvée</i>",
    "φυτάλιος": "ῠᾰ ; <i>chez les Épq. ῡ p. nécessité métr</i>.",
    "ἠπύω": "ῠ <i>prés. et impf.,</i> ῡ <i>fut. et ao</i>.",
    "σπουδάζω": "ᾰ <i>fut., ao., pf. et pl.q.pf. act</i>.",
    "μεθίημι": "ῑ, ATT., <i>qqf</i>. ῐ, IL. <i>v. ci-dessous</i>",
    "τυραννία": "ῠῑ <i>par nécess. prosod</i>.",
    "δάϊος": "ᾱ, <i>v. fin</i>",
    "βάσιλλα": "βᾱ <i>pour</i> βᾰ",
    "ἡρώϊος": "ω <i>bref</i>",
    "μυρίος": "ῡ, <i>non</i> ῠ, DRAC. <i>p. 65, 19</i>",
    "ἀντικρύ": "ῠ, <i>v. ci-dessous</i>",
    "σκύφειος": "ῠ, <i>par nécess. prosod</i>. ῡ",
    "φιλέω": "ῐ, <i>v. ci-dessous</i>",
    "μανόστημος": "ᾱ, <i>par nécessité métr</i>. ᾰ",
    "ὀσφύς": "ῡ <i>aux cas dissyll</i>.",
    "ἀράχνιον": "<i>v. la quantité ci-dessous</i>",
    "ἱλάειρα": "ῐᾰει, <i>sel. d’autres,</i> ῑᾱει",
    "ὑδατοσύδνη": "ῠ, <i>par nécess. prosod</i>. ῡδᾰ",
    "ἐρινύς": "ῑ, ῡ <i>dans les formes trisyll.,</i> ῠ <i>dans les formes tétrasyll</i>.",
    "ὑδατοθρέμμων": "ῠᾰ, <i>par nécess. pros</i>. ῡ",
    "χειρότμητος": "<i>noté</i> χειροκμητος <i>par Hercher</i>",
    "ἀπαμάω": "αμ, <i>v. ci-dessous</i>",
    "ῥυσίκοσμος": "ῠ <i>irrég.,</i> ῐ",
    "βελτίων": "ῑ <i>att., mais voy. ci-dessous</i>",
    "πορνίδιον": "<i>p. exc</i>. ῑδ <i>au lieu de</i> ῐδ",
    "νεανίας": "ᾱᾱ ; <i>qqf. par syniz. νεα- en une seule longue, chez les Att</i>.",
    "κορνικολανοί": "ᾱ <i>de</i> Cornĭcŭlānus",
    "συγκακύνω": "ᾰῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ἰοειδής": "ῐ, <i>par licence p</i>. ῑ",
    "ἐάω": "ᾰ <i>au prés. et à l’impf. ;</i> ᾱ <i>aux autres temps act. pass. et moy</i>.",
    "συγκαλλύνω": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ἀλάμπετος": "ᾱ <i>par lic</i>.",
    "στεροπηγερέτα": "ᾰ, <i>mais</i> ᾱ <i>par position</i>",
    "σέλινον": "ῑ, <i>v. ci-dessous</i>",
    "ἄγνοια": "ᾰ <i>fin</i>.",
    "προσδιακρίνω": "ῑ <i>prés.,</i> ῐ <i>fut</i>.",
    "χελύσκιον": "<i>graphie</i> χελίσκιον pour Kühn",
    "συναποδύρομαι": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ἀνήρ": "ᾰ, <i>mais v. ci-dessous</i>",
    "φλαβιανός": "ᾱᾰ <i>au lieu de</i> ᾱᾱ",
    "σκαλμίδιον": "ῐδ, <i>mais</i> ῑδ <i>par nécessité prosod</i>.",
    "παραλύω": "ῡ, <i>mais voy. fin</i>",
    "ἀμπελοφύτωρ": "ῡ <i>pour</i> ῠ",
    "προσαμύνω": "ᾰῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ἀπεῖπον": "ἀπο- <i>à l’arsis</i>",
    "κονίω": "ῑ <i>à tous les temps</i>",
    "βρίθω": "ῑ <i>à tous les temps</i>",
    "κλέπτρια": "ῐᾰ, <i>gén</i>. ᾱ",
    "σταμίν": "ῑ, <i>par nécessité prosod</i>. ῐ",
    "μυδαλόεις": "ῠᾰ, <i>par nécess. prosod</i>. ῡᾰ",
    "ἀνολβία": "ῑ <i>par licence</i>",
    "παλαιός": "ᾰ, <i>v. ci-dessous</i>",
    "φυταλιά": "ῠτᾰ ; <i>chez les Épq. ῡτᾰ p. nécessité métr</i>.",
    "περιφαής": "ᾰ ; <i>p. excep</i>. ᾱ",
    "τίω": "<i>au prés</i>. ῑ̆ <i>épq.,</i> ῐ <i>att. ; aux autres temps</i> ῑ",
    "ὑαλόχροος": "ῠ, <i>p. exc</i>. ῡ",
    "προσβαθύνω": "ᾰῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "ὀϊζύω": "ῡ <i>à tous les temps, excepté au prés. dans Hom., v. ci-dessous</i>",
    "συγκρατύνω": "ᾰ, ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "χρύσεος": "ῡ <i>dans Hom. et les Épq. ; p. suite</i> χρυσέη, χρυσέου, χρυσέῳ, <i>etc. touj. dissyll</i>. IL. <i>1, 15, 374, etc. ;</i> ῠ <i>chez les Lyr. et dans les chœurs des Trag</i>.",
    "ὑπάτιος": "ῠ, <i>par exc. ῡ à l’arsis,</i> ᾰ",
    "παράνοια": "ᾱ <i>fin</i>.",
    "ἀντιπέραιος": "ᾰ <i>fin</i>.",
    "τρόπις": "ῐ <i>pour</i> ῑ",
    "πέλεκυς": "ῠ <i>au nom. et à l’acc. sg. mais v. ci-dessous</i>",
    "ἠλεκτρύων": "-εκτρ- <i>bref</i>",
    "πιφαύσκω": "ῑ̆ <i>à l’act.,</i> ῐ <i>au moy</i>.",
    "δαναΐδης": "ᾰᾰῐ, <i>mais v. ci-dessous</i>",
    "μυλιάω": "ῠ, <i>par nécess. métr</i>. ῡ",
    "θυγάτηρ": "ῠᾰ, ῡ <i>dans toutes les formes tétrasyll</i>.",
    "συμπαρασύρω": "ῡ <i>prés. et ao.1,</i> ῠ <i>fut. et ao.2</i>",
    "τριάκοντα": "ᾱκ, <i>postér. épq</i>. ᾰκ",
    "συναθύρω": "ᾱ ; ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "πικρός": "ῑ ; <i>par exc</i>. ῐ, <i>v. ci-dessous</i>",
    "ἀχήν": "ᾱ, <i>mais v</i>. ἀχηνία",
    "ἱερός": "ῐ, <i>mais v. ci-dessous</i>",
    "πῦρ": "ῡ <i>aux cas monosyll.,</i> ῠ <i>aux cas dissyll</i>.",
    "φονεύς": "ᾰ <i>p. exc. dans l’acc</i>. φονέα, EUR. <i>Hec. 876</i>",
    "χιόνεος": "ῐ, <i>p. exc</i>. ῑ <i>à l’arsis</i>",
    "ἰξύς": "ῡ <i>nom. et acc. sg. ;</i> ῠ <i>aux cas trisyll</i>.",
    "ἐξυφαίνω": "ῠ <i>au prés</i>.",
    "πτύρω": "ῡ <i>prés. et ao. ;</i> ῠ <i>fut. et ao.2 pass</i>.",
    "χιονόπεζα": "ῐ, <i>p. exc</i>. ῑ",
    "εἰλύω": "ῡ, <i>postér</i>. υ",
    "χεριάρης": "ᾰρ, <i>au gén</i>. ᾱ <i>fin</i>.",
    "ἀπείρατος³": "ρᾰ <i>p. licence poét. p</i>. ρᾱ",
    "ποίας": "οι <i>bref</i>",
    "τίταρος": "ῑ <i>pour</i> ῐ, ᾰ",
    "ὑμνέω": "ῡ, <i>p. exc</i>. ῠ, <i>v. ci-dessous</i>",
    "φοινικόεις": "ῑ, -οει- <i>et</i> -οε- <i>forment synizèse</i>",
    "συνέσιος": "ῠ, <i>par exc</i>. ῡ, A. PL. <i>38</i>",
    "χιών": "ῐ, <i>chez les Épq. qqf. ῑ aux cas où il est suivi de deux voyelles brèves</i>",
    "ὄρνις": "ῑ <i>dans les formes trisyll. ; dans les dissyll. il est commun dans Homère, long dans Aristophane, bref dans les Tragiques, excepté à l’acc. pl. poét</i>. ὄρνις",
    "σῦς": "ῡ <i>aux cas monosyll. ailleurs</i> ῠ",
    "ὀϊζύς": "ῡ <i>aux cas dissyll. ῠ aux cas trisyll</i>.",
    "κονία": "ῐ ; <i>v. ci-dessous</i>",
    "δαΐζω": "ᾰ, <i>v. fin</i>",
    "ἁβρός": "ᾱ, <i>v. ci-dessous</i>",
    "γένυς": "ῠ, <i>mais v. ci-dessous</i>",
    "καλοβάμων": "κᾰ <i>par licence pour</i> κᾱ, ϐᾱ",
    "συναισχύνω": "χῡ <i>prés.,</i> χῠ <i>fut</i>.",
    "ἀνίημι": "ῐ, <i>mais v. fin de l’article</i>",
    "συγκατευθύνω": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "μαιμάω": "ᾱ, IL. <i>20, 490</i>",
    "μυοδόχος": "<i>irrég</i>. ῡ",
    "ἱμάς": "ῐ, <i>v. ci-dessous</i>",
    "φλύω": "ῠ <i>prés. et impf. ;</i> ῡ <i>fut. et ao., mais ῠ lorsque la syllabe suiv. est brève,</i> ANTH. <i>7, 351</i>",
    "ἀμαρυγή": "ᾰᾰῠ, <i>épq</i>. ῡ",
    "ἠλεκτρυώνη": "-εκτρ <i>bref</i>",
    "φιλοθουκυδίδης": "ῐῡῐ ; <i>p. lic. poét</i>. ῠ",
    "ποία": "οι <i>bref</i>",
    "βαθύνω": "ᾰ, ῡ <i>prés. et ao</i>., ῠ <i>fut</i>.",
    "ἐρητύω": "ῡ <i>devant</i> σ <i>et devant une syll. longue ;</i> ῠ <i>devant une syll. brève</i>",
    "ἰχθύς": "ῡ <i>aux cas dissyllabiques, ῠ aux cas trisyllabiques</i>",
    "ὑλακόμωρος": "ῡ <i>à l’arsis,</i> ᾰ",
    "τύλη": "ῠ <i>v. ci-dessous</i>",
    "τρισσοκέφαλος": "ᾰ, ᾱ <i>p. licence</i>",
    "φημί": "ᾰ <i>sauf dans</i> φασί, φάς <i>et</i> φᾶσα ; <i>p. except. φάναι avec</i> ᾱ, EUB. (ATH. <i>8</i> c)",
    "ἀπό": "ᾰ, <i>mais v. fin</i>",
    "ἀΐσσω": "ᾱ HOM. ; ᾰ PD. <i>et</i> TRAG.",
    "διά": "ῐᾰ, <i>mais v. fin</i>",
    "σφραγίς": "ᾱῑ, <i>postér</i>. ῐ, <i>v. ci-dessous</i>",
    "κόνις": "ῐ <i>dev. une voy</i>.",
    "ὑαλόεις": "ῠ, <i>p. exc</i>. ῡ <i>à l’arsis ;</i> ᾰ",
    "πίνω": "ῑ <i>prés. et impf., au fut</i>. ῑ <i>épq. et</i> ῐ <i>v. ci-dessous ; à l’ao</i>. ῐ <i>excepté à l’impér</i>. πῖθι",
    "ὑαλοειδής": "ῠ, <i>par exc</i>. ῡ <i>à l’arsis ;</i> ᾰ",
    "ἀρτύω": "ῠ <i>prés. impf. pf. ;</i> ῡ <i>fut. et ao</i>.",
    "ἀνακρίνω": "ῑ <i>prés.,</i> ῐ <i>fut</i>.",
    "πολύτιτος": "<i>irrég</i>. ῑ",
    "χιονόεις": "ῐ, <i>p. exc</i>. ῑ",
    "ὑποχετεύω": "ῠ, <i>p. exc</i>. ῡ",
    "ἀΐω¹": "ᾱ <i>à l’arsis</i>",
    "ἄγαν": "ᾰᾱ, <i>postér</i>. ᾰᾰ, <i>v. ci-dessous</i>",
    "ἀποδύω": "<i>exemple erroné de Bailly :</i> ἀποδυσάμενος, OD. <i>5, 349,</i> après avoir ôté le voile (divin que Leukothéè donne à Ulysse), <i>on lit aujourd’hui</i> ἀπολυσάμενος",
    "συγκατασύρω": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
    "γάρ": "ᾰ ; <i>v. ci-dessous</i>",
    "μητίω": "ῐ <i>dev. une voy. ;</i> ῑ <i>dev</i>. σ",
    "διογενής": "ῐ, <i>épq</i>. ῑ <i>v. ci-dessous</i>",
    "λινόδρυς": "ῐ ; ῡ <i>nomin</i>.",
    "λεπτόθριος": "ῐ <i>irrég</i>.",
    "σικελία": "σῐ, <i>v. ci-dessous</i>",
    "ποιπνύω": "υ <i>au prés. et à l’impf. bref devant une syllabe brève, long devant une longue, partout ailleurs long</i>",
    "σκίδνημι": "ᾱ <i>fin</i>.",
    "συμπορσύνω": "ῡ <i>prés.,</i> ῠ <i>fut</i>.",
}
